language: node_js
node_js:
  - "0.10"
before_install: npm install -g grunt-cli
env:
  global:
    - secure: Yu4uDNN6y4d2cCwAEg4fyvN0oRWbCqNaHgL7kyxYXybpfJ0uW7BXF/4b0InV24th1qFTbC5m+yyzvgxamIo2YtkGDCryoy6tsNvlm71yqTaq9Z2BayBLDrMU7P4MnXswA5OAEMMu2AIGY8dk1n9uk2cGlFhkAjhDnYPN2Ly3Cd0=
    - secure: ISrGBuvdhvq112x3YhMK9YkhhHrZoJCrRvXu3gAWKDaMIdMOXZbAKqxqdVOl8pMGVCwQvYppWL6nGFg2xKP4cYc/8GybuYOfhzVlV70v+BT5gyMBd8SaMfpeJKibQIHyRKpriOhhVFa7V/fKZtLl/WmQ/XrVLlKdHe4/1CylYJE=
